pipeline:
  docker:
    repo: armswarm/alertmanager
    build_args:
      - ALERTMANAGER_VERSION=0.4.2
      - VCS_REF=${DRONE_COMMIT_SHA}
      - VCS_URL=${DRONE_REPO_LINK}
      - BUILD_DATE=${DRONE_BUILD_CREATED}
      - PROJECT_NAME=${DRONE_REPO}
    tag: [ "latest", "0.4", "0.4.2" ]
    when:
      branch: master
      event: push

  slack:
    when:
      status: [ failure, success ]
